### ISSUE TITLE
Implement "Sumá tu Comercio", about y contact form

### ISSUE THREAD

**Issue by pwolfus** [cauda-app/front#30]

**Comment by grijos** [comment]
@pwolfus Do we have empty screens already connected and ready?

**Comment by ramirotw** [comment]
> @pwolfus Do we have empty screens already connected and ready?

No, nothing. Just add empty files and start from scratch.

**Comment by grijos** [comment]
@pwolfus Will need wording for this screen. It is already implemented with filler text.
