### ISSUE TITLE
Wrap up homepage

### ISSUE THREAD

**Issue by pwolfus** [cauda-app/front#31]

**Comment by grijos** [comment]
@pwolfus Updated WIP Home. Brand logos coming soon.

![localhost_3000_my-shop (2)](https://user-images.githubusercontent.com/1039122/83093531-01806c00-a076-11ea-8c85-463852a00984.png)

**Comment by grijos** [comment]
![IMG_2669](https://user-images.githubusercontent.com/1039122/83099305-5a0a3600-a083-11ea-9505-5993c51f9183.PNG)
