### ISSUE TITLE
Add shop's poster with the QR code

### ISSUE THREAD

**Issue by pwolfus** [cauda-app/front#45]

**Comment by grijos** [comment]
@ramirotw 

- As it doesn't need all the common <Layout> stuff I created a simple plain view. I think it will need another type of empty Layout for this. That's in your hands.
- This screen is now on public/shop-poster.html for you to grab its code.
- It has no CSS dependencies.
- Please let me know when you implement the new empty Layout and add the dynamic QR code, so I can take a closer look and make final adjustments.

**Comment by grijos** [comment]
@pwolfus This is how it looks when printing this page from Chrome.

- The header and footer is automatically hidden.
- The poster will fit any page size. It should look good on both A4 and Legal paper sizes.
- The blue QR is a placeholder image. @ramirotw can switch it with the real ones.

<img width="1362" alt="Screen Shot 2020-05-24 at 15 16 28" src="https://user-images.githubusercontent.com/1039122/82761540-97479d00-9dd1-11ea-849d-87bb0f056937.png">
