### ISSUE TITLE
Agregar cantidad de turnos activos en la fila en la búsqueda y en la tarj del comercio

### ISSUE THREAD

**Issue by pwolfus** [cauda-app/front#80]

**Comment by grijos** [comment]
@pwolfus @ramirotw @nicosampler Está implementado esto y faltan estilos? o no existe todavía?

**Comment by grijos** [comment]
@nicosampler @ramirotw @pwolfus Ahí mandé un commit a ciegas. Son dos textos dependiendo la cantidad de gente en la fila:

Si hay mucha gente:
`<strong>XX personas en la fila</strong>`

Y si no hay nadie:
`No hay nadie en la fila`

El icono que puse debería ser este: https://fontawesome.com/icons/ellipsis-h?style=regular
Espero que comunique la idea de "espera" y al mismo tiempo de gente "puntitos" en una fila. Con suerte todos usan chat en el celu y ven esos puntitos como que tienen que esperar algo.
